import sys
reload(sys)
sys.setdefaultencoding('utf8')

channels = [
	['BNT','online-bnt','bnt.png'],
	['BNT 2','online-bnt-2','bnt2.png'],
	['Nova Tv','online-nova-tv','nova-1.png'],
	['TV 7','online-tv-7','tv7-1.png'],
	['BTV','btv-online','btv.png'],
	['Fashion Tv','fashion-tv-online','fashion.png'],
	['PVTV','pvtv-online','pvtv.png'],
	['Fox','fox-online','fox-1.png'],
	['24 Kitchen','24-kitchen-online','24kitchen-2.png'],
	['News7 External','news7-%d0%b7%d0%b0-%d1%87%d1%83%d0%b6%d0%b1%d0%b8%d0%bd%d0%b0','news7-1.png'],
	['News7','news7-online','news7-1.png'],
	['Nova Tv External','nova-tv-za-chujbina','nova.png'],
	['BTV Lady','online-btv-lady','btvlady.png'],
	['Diema','online-diema','diema.png'],
	['BTV Action','online-btv-action','btvaction.png'],
	['BNT HD','bnt-hd-online','bnthd-1'],
	['HBO','hbo-online','hbo-1.png'],
	['HBO 2','hbo-2-online-2','hbo2-1.png'],
	['Cinemax','cinemax-online','cinemax-1.png'],
	['Cinemax 2','cinemax-2-online','cinemax2-1.png'],
	['Axn','axn-online','axn.png'],
	['Tv 1000','tv-1000-online','tv1000-1.png'],
	['Fox Crime','fox-crime-online','foxcrime-1.png'],
	['Fox Life','fox-life-online','foxlife.png'],
	['BTV Comedy','online-btv-comedy','btvcomedy.png'],
	['BTV Cinema','btv-cinema-online','btvcinema.png'],
	['Diema Family','online-diema-family','diemaf.png'],
	['Kino Nova','online-kino-nova','kinonova.png'],
	['MTV Hits','mtv-hits-online','mtvhits-1.png'],
	['Box Tv','box-tv-online','box-1.png'],
	['Planeta Folk','planeta-folk-online','planetafolk.png'],
	['City Tv','city-tv-online','citytv.png'],
	['Planeta HD','online-planeta-hd','planetahd.png'],
	['Fan Tv','online-fan-tv','fantv.png'],
	['Balkanika Tv','online-balkanika-tv','balkanika.png'],
	['Planeta Tv','online-planeta-tv','planeta.png'],
	['The Voice','online-the-voice','thevoice.png'],
	['Comedy Central','comedy-central-online','comedyc-1.png'],
	['Disney Junior','disney-junior-online','junior.png'],
	['Boomerang','boomerang-online','boomerang-1.png'],
	['Nickelodeon','nickelodeon-online','nickelodeon-1.png'],
	['Disney Channel','disney-channel-online','disney-2.png'],
	['Ekids','online-ekids','ekids.png'],
	['Cartoon Network','online-cartoon-network','cartoon.png'],
	['Super 7','online-super-7','super7-1.png'],
	['Diema Sport','diema-sport-online','diemasport-1.png'],
	['Diema Sport 2','diema-sport-2-online','diemasport2-1.png'],
	['Eurosport','online-eurosport','eurosport.png'],
	['Eurosport 2','eurosport-2-online','eurosport2-1.png'],
	['Nova Sport','online-nova-sport','novasport.png'],
	['Ring Bg','online-ring-bg','ringbg.png'],
	['Ntv Spor','online-ntv-spor','ntvspor.png'],
	['Fox Tv','online-fox-tv','2012/01/fox.png'],
	['ATV','online-atv','2012/01/atv.png'],
	['Star Tv','online-star-tv','2012/01/star.png'],
	['Kanal D','online-kanal-d','2012/01/kanal-d.png'],
	['Show Tv','online-show-tv','2012/01/show.png'],
	['TLC','tlc-online','tlc-1.png'],
	['Viasat History','viasat-history-online','viasat_history.png'],
	['Viasat Nature','viasat-nature-online','viasat_nature.png'],
	['Viasat Explorer','viasat-explorer-online','viasat_explorer.png'],
	['Nat Geo Wild','nat-geo-wild-online','natgeowild.png'],
	['Animal Planet','animal-planet-online','animalplanet.png'],
	['History Channel','history-channel-online','history-1.png'],
	['Discovery Channel','online-discovery','discovery.png'],
	['National Geographic','online-national-geographic','ng.png'],
]